const designs=[
{title:'Musik & Gemeinschaft',short:'Ein Haus für Begegnung, Veranstaltungen und Musik.',description:'Café, Kindermesse und Musikerstammtisch bilden die offene Basis. Darüber liegen ein flexibler Veranstaltungssaal und das Orgel-Lab als musikalischer Abschluss.',base:5,floors:['Erdgeschoss','Obergeschoss','Halbgeschoss'],texts:['Das Café ist ein offener Treffpunkt für die Gemeinde. Kindermesse und Musikerstammtisch ergänzen das gemeinschaftliche Angebot; Lager- und Nebenräume unterstützen den Betrieb.','Der großzügige Saal bietet Raum für Feiern, Konzerte und Zusammenkünfte. Eine mobile Trennwand ermöglicht unterschiedliche Nutzungen. Die sichtbare Holzkonstruktion prägt die warme Atmosphäre.','Das Orgel-Lab bietet Raum für musikalisches Arbeiten, Experimentieren und Proben. Unter den schrägen Dachflächen entsteht ein konzentrierter Rückzugsort.']},
{title:'Wohnen & Begegnung',short:'Privates Wohnen, öffentlicher Treffpunkt und Raum zum Lesen.',description:'Eine Wohnung im Erdgeschoss, Café und Veranstaltung im Obergeschoss und eine Bibliothek unter dem Dach verbinden Alltag, Gemeinschaft und Rückzug.',base:18,floors:['Erdgeschoss','Obergeschoss','Halbgeschoss'],texts:['Die Wohnung schafft einen privaten, dauerhaft genutzten Bereich. Wohnen, Küche, Schlaf- und Kinderzimmer sowie Nebenräume sind funktional angeordnet.','Café und Veranstaltungsbereich bilden den kommunikativen Mittelpunkt. Die flexible Nutzung ermöglicht alltägliche Begegnungen ebenso wie Feiern, Vorträge und kleinere Konzerte.','Die Bibliothek ist ein ruhiger Ort zum Lesen, Lernen, Arbeiten und für kleinere Treffen. Sichtbares Holz und die Dachschrägen verleihen dem Raum einen konzentrierten Charakter.']},
{title:'Arbeiten & Kultur',short:'Café, Coworking und Kultur im bestehenden Ensemble.',description:'Ein offener Empfang mit Café, flexible Arbeitsplätze und Raum für Veranstaltungen und Ausstellungen beleben das Haus über den Tag. Der Durchgang zur Kirche verbindet das Ensemble.',base:30,floors:['Erdgeschoss','Obergeschoss','Dachgeschoss'],texts:['Café und Empfang für Seminare und Veranstaltungen bilden die öffentliche Basis. Die Rezeption dient als Anlaufstelle für Workshops, Kurse und Seminare.','Der Coworking-Space ermöglicht konzentriertes Arbeiten, gemeinsames Lernen, Besprechungen und kleinere Workshops. Büros und eine Teeküche ergänzen das Angebot.','Veranstaltungen, Ausstellungen, Präsentationen und Vorträge finden hier ihren Raum. Der direkte Durchgang zur Kirche stärkt die räumliche Verbindung zum bestehenden Ensemble.']}
];
let current=0,floor=0,galleries=[],items=[],itemIndex=0,zoom=1;const $=s=>document.querySelector(s),page=n=>`page-${n}.webp`;
$('#cards').innerHTML=designs.map((d,i)=>`<button class="card" data-design="${i}"><div class="card-image"><img src="hero-${i+1}.webp" alt="Außenvisualisierung Entwurf 0${i+1}" loading="lazy"><span class="card-index">0${i+1}</span></div><h3>${d.title}</h3><p>${d.short}</p><span class="card-link">Entwurf erkunden <span>↗</span></span></button>`).join('');
$('#design-tabs').innerHTML=designs.map((d,i)=>`<button role="tab" id="tab-${i}" aria-controls="explorer-panel" data-design="${i}">0${i+1} <span> / ${d.title}</span></button>`).join('');$('.explorer-body').id='explorer-panel';$('.explorer-body').setAttribute('role','tabpanel');
$('#posters').innerHTML=designs.map((d,i)=>`<button class="poster" data-poster="${i}"><img src="${page(i+1)}" alt="Originalplakat Entwurf 0${i+1}" loading="lazy"><span>Entwurf 0${i+1}<span>Plakat öffnen ↗</span></span></button>`).join('');
function update(){const d=designs[current];$('#design-number').textContent=`ENTWURF 0${current+1}`;$('#design-title').textContent=d.title;$('#design-description').textContent=d.description;$('.explorer-body').setAttribute('aria-labelledby',`tab-${current}`);document.querySelectorAll('#design-tabs button').forEach((b,i)=>{b.setAttribute('aria-selected',i===current);b.tabIndex=i===current?0:-1});$('#floor-tabs').innerHTML=d.floors.map((f,i)=>`<button role="tab" aria-selected="${i===floor}" tabindex="${i===floor?0:-1}" data-floor="${i}">${f}<span>↗</span></button>`).join('');$('#plan-title').textContent=d.floors[floor];$('#plan-img').src=`plan-${d.base+floor}.webp`;$('#plan-img').alt=`Entwurf 0${current+1} · Grundriss ${d.floors[floor]}`;$('#floor-description').textContent=d.texts[floor];$('#gallery-number').textContent=`Entwurf 0${current+1}`;$('#gallery').innerHTML=(galleries[current]||[]).map((g,i)=>`<button data-image="${i}"><img src="${g.src}" alt="Entwurf 0${current+1}: ${g.floor}, Visualisierung ${i+1}" loading="lazy"><span class="gallery-caption">${g.floor}<span>↗</span></span></button>`).join('')}
function show(list,index=0){items=list;itemIndex=index;zoom=1;updateViewer();$('#viewer').showModal();document.body.style.overflow='hidden'}
function updateViewer(){const item=items[itemIndex];$('#viewer-title').textContent=item.title;$('#viewer-img').src=item.src;$('#viewer-img').alt=item.title;$('#viewer-count').textContent=`${itemIndex+1} / ${items.length}`;$('#viewer-prev').disabled=itemIndex===0;$('#viewer-next').disabled=itemIndex===items.length-1;zoom=1;applyZoom()}
function applyZoom(){$('#viewer-img').style.width=`${zoom*100}%`;$('#viewer-img').style.height=`${zoom*100}%`;$('#zoom-value').textContent=`${Math.round(zoom*100)}%`;$('#zoom-out').disabled=zoom<=1;$('#zoom-in').disabled=zoom>=4}
function openPlan(){show(designs[current].floors.map((f,i)=>({src:page(designs[current].base+i),title:`Entwurf 0${current+1} · ${f}`})),floor)}
document.addEventListener('click',e=>{const d=e.target.closest('[data-design]'),f=e.target.closest('[data-floor]'),h=e.target.closest('[data-hero]'),g=e.target.closest('[data-image]'),p=e.target.closest('[data-poster]');if(d){current=+d.dataset.design;update();if(d.classList.contains('card'))$('#plaene').scrollIntoView({behavior:'smooth'})}if(f){floor=+f.dataset.floor;update();$(`[data-floor="${floor}"]`).focus()}if(h){const i=+h.dataset.hero;$('#hero-img').src=`hero-${i+1}.webp`;$('#hero-img').alt=`Außenvisualisierung Entwurf 0${i+1}`;$('#hero-label').textContent=`0${i+1} / ${designs[i].title}`;document.querySelectorAll('[data-hero]').forEach((b,j)=>{b.classList.toggle('active',j===i);b.setAttribute('aria-pressed',j===i)})}if(g)show(galleries[current].map((g,i)=>({src:g.src,title:`Entwurf 0${current+1} · ${g.floor} · Visualisierung ${i+1}`})),+g.dataset.image);if(p)show(designs.map((d,i)=>({src:page(i+1),title:`Originalplakat · Entwurf 0${i+1}`})),+p.dataset.poster)});
$('#plan-open').onclick=openPlan;$('#enlarge-plan').onclick=openPlan;$('#open-drawing').onclick=()=>show(Array.from($('#drawing').options).map(o=>({src:page(designs[current].base + +o.value),title:`Entwurf 0${current+1} · ${o.textContent}`})),$('#drawing').selectedIndex);
$('#viewer-close').onclick=()=>$('#viewer').close();$('#viewer').addEventListener('close',()=>{document.body.style.overflow=''});$('#viewer').onclick=e=>{if(e.target===$('#viewer'))$('#viewer').close()};$('#zoom-in').onclick=()=>{zoom=Math.min(4,zoom+.5);applyZoom()};$('#zoom-out').onclick=()=>{zoom=Math.max(1,zoom-.5);applyZoom()};$('#viewer-prev').onclick=()=>{if(itemIndex>0){itemIndex--;updateViewer()}};$('#viewer-next').onclick=()=>{if(itemIndex<items.length-1){itemIndex++;updateViewer()}};
document.addEventListener('keydown',e=>{if($('#viewer').open){if(e.key==='ArrowRight')$('#viewer-next').click();if(e.key==='ArrowLeft')$('#viewer-prev').click()}else if(e.target.closest('[role=tablist]')&&['ArrowRight','ArrowLeft','ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const list=e.target.closest('[role=tablist]'),buttons=[...list.querySelectorAll('button')];let i=buttons.indexOf(e.target);i=e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(['ArrowRight','ArrowDown'].includes(e.key)?1:-1)+buttons.length)%buttons.length;buttons[i].click();list.querySelectorAll('button')[i].focus()}});
let touchX=0;$('#viewer-stage').addEventListener('touchstart',e=>touchX=e.changedTouches[0].clientX,{passive:true});$('#viewer-stage').addEventListener('touchend',e=>{if(zoom!==1)return;const dx=e.changedTouches[0].clientX-touchX;if(Math.abs(dx)>70)$(dx<0?'#viewer-next':'#viewer-prev').click()},{passive:true});
$('.menu').onclick=()=>{const open=$('nav').classList.toggle('open');$('.menu').setAttribute('aria-expanded',open);$('.menu').setAttribute('aria-label',open?'Menü schließen':'Menü öffnen')};document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>{$('nav').classList.remove('open');$('.menu').setAttribute('aria-expanded','false')});
update();fetch('galleries.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{galleries=data;update()}).catch(()=>{$('#gallery').innerHTML='<p>Die Bilder konnten nicht geladen werden. Alle Visualisierungen sind in der <a href="pfarrerstall-judith-steinacher.pdf">Gesamtdokumentation</a> enthalten.</p>'});
